# Cohesif BTP — contenu des pages métier générées (lu par tools/build_metiers.py)
# Les pages toiture-couverture.html et facade-ravalement.html restent écrites à la main (simulateurs 3D).
# Icônes disponibles : voir ICONES dans build_metiers.py.

METIERS = [
  {
    'slug': 'renovation-appartement-maison',
    'nom': 'Rénovation complète',
    'service': 'renovation',
    'titre': 'Rénovation complète d\'appartement et de maison à Paris & IDF | Cohesif BTP',
    'description': 'Rénovation complète d\'appartement, de maison ou de bureaux à Paris, en Île-de-France et partout en France : cuisine, salle de bain, électricité, plomberie, redistribution, isolation. Un seul interlocuteur, devis sous 48h.',
    'badge': 'Rénovation · Paris, Île-de-France et toute la France',
    'h1': 'Rénovation complète d\'appartement et de maison : <span class="accent">un seul interlocuteur, de la démolition aux finitions.</span>',
    'lead': 'Cuisine, salle de bain, électricité, plomberie, cloisons, sols et peinture : Cohesif BTP coordonne tous les corps de métier de votre rénovation, avec un chef de projet unique, un bureau d\'études intégré et un planning écrit.',
    'trust': ['Devis détaillé sous 48h', 'Un chef de projet unique', 'Bureau d\'études intégré', 'Planning écrit et tenu'],
    'carte_titre': 'Ce que nous réalisons',
    'carte': ['Rénovation complète d\'appartements et de maisons', 'Cuisines et salles de bain clés en main', 'Redistribution des pièces, ouverture de murs', 'Électricité et plomberie remises aux normes', 'Isolation, menuiseries, ventilation', 'Réhabilitation de bureaux et commerces'],
    'prestations_titre': 'Toute votre rénovation, <span class="accent">sous un seul toit.</span>',
    'prestations_desc': 'Plus besoin de coordonner cinq artisans : nous organisons l\'enchaînement des lots pour tenir les délais et le budget.',
    'prestations': [
      ('home', 'Rénovation clés en main', 'Du curage à la remise des clés : démolition, réseaux, cloisons, sols, murs, plafonds, menuiseries et finitions.'),
      ('drop', 'Cuisine & salle de bain', 'Dépose, plomberie, électricité, étanchéité sous carrelage (SPEC), faïence, meubles et équipements posés.'),
      ('layers', 'Redistribution des espaces', 'Création ou suppression de cloisons, ouverture de murs porteurs avec étude de structure et poutre adaptée.'),
      ('bolt', 'Électricité & plomberie', 'Mise aux normes du tableau et des circuits (NF C 15-100), remplacement des colonnes et des évacuations.'),
      ('thermo', 'Rénovation énergétique', 'Isolation, fenêtres, ventilation et chauffage, avec les aides possibles. <a href="aides-financement.html#simulateur">Simulez vos aides</a>.'),
      ('building', 'Bureaux & commerces', 'Réhabilitation de locaux professionnels, en site occupé si besoin, par phases pour ne pas interrompre l\'activité.'),
    ],
    'etapes': [
      ('Visite & relevé', 'Nous mesurons, photographions et listons vos attentes, contraintes et priorités.'),
      ('Plans & devis détaillé', 'Plans d\'aménagement, choix des matériaux et devis poste par poste sous 48h.'),
      ('Démarches & planning', 'Autorisation de la copropriété si besoin, commandes, planning écrit lot par lot.'),
      ('Chantier & réception', 'Chef de projet unique, point hebdomadaire, réception contradictoire et levée des réserves.'),
    ],
    'savoir_titre': 'Avant de rénover, <span class="accent">les points à anticiper.</span>',
    'savoir': [
      'En copropriété, toucher aux parties communes, à un mur porteur ou à l\'aspect extérieur (fenêtres) demande l\'accord de l\'assemblée générale.',
      'Ouvrir un mur porteur impose une étude de structure et un renfort dimensionné : jamais d\'ouverture « à l\'œil ».',
      'Dans un logement construit avant 1997, un repérage amiante avant travaux est obligatoire avant toute démolition.',
      'Le règlement de copropriété fixe souvent les horaires de chantier bruyant : le planning en tient compte.',
      'Les délais des cuisines, menuiseries sur mesure et carrelages se commandent tôt : ils conditionnent la date de fin.',
    ],
    'savoir_carte': ('Un logement ancien ?', 'Avant 1997, la présence d\'amiante est possible dans les colles, dalles de sol ou enduits. Notre pôle désamiantage organise le repérage et le retrait avant les travaux.', 'desamiantage.html', 'Le désamiantage'),
    'pros': [
      ('Un seul interlocuteur', 'Un chef de projet coordonne tous les corps de métier et répond à vos questions, du devis à la réception.'),
      ('Bureau d\'études intégré', 'Plans, structure, optimisation du budget dès la conception : vous payez le juste prix, sans mauvaise surprise.'),
      ('Des garanties claires', 'Garantie de parfait achèvement, biennale et décennale : les garanties légales s\'appliquent à nos travaux.'),
    ],
    'faq': [
      ('Combien de temps dure la rénovation complète d\'un appartement ?', 'Pour un appartement de 60 à 80 m², comptez en général deux à quatre mois de travaux, selon l\'ampleur (redistribution, électricité, plomberie) et les délais de livraison des cuisines et menuiseries. Le planning précis figure dans le devis.'),
      ('Quel budget prévoir pour une rénovation complète ?', 'À titre indicatif, un rafraîchissement (sols, peinture) se situe souvent entre 250 et 500 € HT par m², une rénovation complète entre 800 et 1 500 € HT par m², et une rénovation lourde avec redistribution au-delà. Le devis détaillé après visite donne le montant exact.'),
      ('Peut-on habiter le logement pendant les travaux ?', 'C\'est possible pour une rénovation partielle, pièce par pièce. Pour une rénovation complète, il est en général plus rapide et plus confortable de libérer le logement : cuisine et salle de bain sont indisponibles plusieurs semaines.'),
      ('Peut-on ouvrir un mur porteur dans un appartement ?', 'Oui, après une étude de structure qui dimensionne le renfort (poutre métallique ou béton) et, en copropriété, avec l\'accord de l\'assemblée générale, car le mur porteur est une partie commune. Notre bureau d\'études prépare ce dossier.'),
      ('Intervenez-vous pour les bureaux et commerces ?', 'Oui. Nous réhabilitons des bureaux et locaux commerciaux, y compris en site occupé, en découpant le chantier en phases pour ne pas interrompre l\'activité.'),
    ],
    'form_travaux': ['Rénovation complète', 'Cuisine', 'Salle de bain', 'Redistribution / ouverture de mur', 'Électricité / plomberie', 'Bureaux / commerce', 'Autre'],
    'form_placeholder': 'Surface, type de logement, pièces concernées, délai souhaité…',
    'liens': [('aides-financement.html', 'Aides & financement', 'Simulez MaPrimeRénov\', CEE, TVA réduite'), ('isolation-combles-murs.html', 'Isolation', 'Combles, murs, planchers, acoustique'), ('desamiantage.html', 'Désamiantage', 'Repérage et retrait avant travaux')],
  },
  {
    'slug': 'gros-oeuvre-maconnerie',
    'nom': 'Gros œuvre & maçonnerie',
    'service': 'gros-oeuvre',
    'titre': 'Gros œuvre & maçonnerie : extension, surélévation, mur porteur | Cohesif BTP',
    'description': 'Gros œuvre et maçonnerie à Paris, en Île-de-France et partout en France : fondations, béton armé, extension, surélévation, ouverture de mur porteur, reprise en sous-œuvre. Bureau d\'études intégré, devis sous 48h.',
    'badge': 'Gros œuvre · Paris, Île-de-France et toute la France',
    'h1': 'Gros œuvre & maçonnerie : <span class="accent">des structures solides, calculées avant d\'être construites.</span>',
    'lead': 'Fondations, béton armé, extension, surélévation, ouverture de mur porteur : Cohesif BTP réalise vos travaux de structure avec son bureau d\'études intégré, des plans et notes de calcul jusqu\'à la réception.',
    'trust': ['Devis détaillé sous 48h', 'Notes de calcul fournies', 'Dossier d\'autorisation préparé', 'Un interlocuteur unique'],
    'carte_titre': 'Ce que nous réalisons',
    'carte': ['Fondations et terrassement', 'Maçonnerie traditionnelle et béton armé', 'Extensions et surélévations', 'Ouverture et reprise de murs porteurs', 'Dalles, planchers, escaliers béton', 'Démolition et curage'],
    'prestations_titre': 'La structure de votre projet, <span class="accent">dans les règles de l\'art.</span>',
    'prestations_desc': 'Le gros œuvre ne pardonne pas l\'approximation : chaque ouvrage est dimensionné par notre bureau d\'études avant d\'être réalisé.',
    'prestations': [
      ('ruler', 'Fondations & terrassement', 'Implantation, terrassement, semelles, longrines ou radier, adaptés à l\'étude de sol et à la charge du bâtiment.'),
      ('bricks', 'Maçonnerie & béton armé', 'Murs en blocs béton, briques ou pierre, voiles, poteaux et poutres en béton armé, chaînages.'),
      ('home', 'Extension & surélévation', 'Agrandissement de plain-pied ou en hauteur, raccordé à l\'existant, de la fondation au clos-couvert.'),
      ('layers', 'Murs porteurs', 'Ouverture ou suppression de murs porteurs avec poutre et poteaux dimensionnés, étaiement pendant les travaux.'),
      ('shield', 'Reprise en sous-œuvre', 'Renforcement de fondations, traitement de fissures structurelles, consolidation après sinistre.'),
      ('tool', 'Démolition & curage', 'Démolition partielle ou totale, curage intérieur, tri et évacuation des gravats vers les filières adaptées.'),
    ],
    'etapes': [
      ('Faisabilité', 'Visite, état de l\'existant, règles d\'urbanisme et besoin d\'étude de sol.'),
      ('Plans & calculs', 'Plans d\'exécution et notes de calcul par notre bureau d\'études, devis détaillé.'),
      ('Autorisations', 'Déclaration préalable ou permis de construire, accord de copropriété si besoin.'),
      ('Exécution & contrôles', 'Étaiement, ferraillage contrôlé avant coulage, réception des ouvrages.'),
    ],
    'savoir_titre': 'Extension, surélévation : <span class="accent">les règles à connaître.</span>',
    'savoir': [
      'Une extension crée de la surface : déclaration préalable jusqu\'à 20 m² (40 m² en zone urbaine d\'un PLU), permis de construire au-delà.',
      'Si la surface totale après travaux dépasse 150 m², le recours à un architecte est obligatoire pour le permis.',
      'Dans les zones exposées au retrait-gonflement des argiles, une étude géotechnique est exigée pour construire une maison neuve.',
      'Une surélévation suppose de vérifier que les murs et fondations existants supportent la charge supplémentaire.',
      'En copropriété, la surélévation et l\'ouverture d\'un mur porteur passent par un vote de l\'assemblée générale.',
    ],
    'savoir_carte': ('Démarches comprises', 'Nous préparons les pièces techniques de votre déclaration préalable ou de votre permis de construire, et coordonnons avec l\'architecte lorsqu\'il est obligatoire.', 'guide-autorisation-travaux-toiture-facade.html', 'Guide des autorisations'),
    'pros': [
      ('Bureau d\'études intégré', 'Notes de calcul, plans d\'exécution et optimisation des quantités de béton et d\'acier dès la conception.'),
      ('Un seul interlocuteur', 'Gros œuvre, toiture, second œuvre : un chef de projet suit l\'ouvrage du terrassement aux finitions.'),
      ('Chantier sécurisé', 'Étaiement, protections, évacuation des gravats et respect du voisinage, en ville comme en pavillon.'),
    ],
    'faq': [
      ('Faut-il un permis de construire pour une extension ?', 'Jusqu\'à 20 m² de surface créée, une déclaration préalable suffit (40 m² en zone urbaine couverte par un PLU). Au-delà, un permis de construire est nécessaire, et le recours à un architecte devient obligatoire si la surface totale dépasse 150 m².'),
      ('Combien de temps durent des travaux d\'extension ?', 'Pour une extension de 20 à 40 m², comptez en général deux à quatre mois de chantier après l\'obtention de l\'autorisation, selon les fondations, le mode constructif et les finitions.'),
      ('Une étude de sol est-elle obligatoire ?', 'Elle est exigée pour construire une maison neuve dans les zones exposées au retrait-gonflement des argiles, et fortement recommandée pour toute extension : elle évite des fondations sous-dimensionnées et des fissures plus tard.'),
      ('Peut-on surélever une maison ou un immeuble ?', 'Souvent oui, si le PLU l\'autorise et si la structure existante supporte la charge. Une étude de structure le vérifie avant tout projet ; en copropriété, l\'assemblée générale doit l\'approuver.'),
      ('Que faire en cas de fissures dans un mur ?', 'Une fissure fine en surface est souvent sans gravité, mais une fissure qui s\'élargit, traverse le mur ou forme un escalier doit être diagnostiquée : elle peut révéler un mouvement de fondation à reprendre en sous-œuvre.'),
    ],
    'form_travaux': ['Extension', 'Surélévation', 'Ouverture de mur porteur', 'Fondations / reprise en sous-œuvre', 'Construction neuve', 'Démolition', 'Autre'],
    'form_placeholder': 'Type de projet, surface, état actuel, délai souhaité…',
    'liens': [('renovation-appartement-maison.html', 'Rénovation complète', 'Appartements, maisons, bureaux'), ('toiture-couverture.html', 'Toiture & couverture', 'Charpente, couverture, zinguerie'), ('guide-autorisation-travaux-toiture-facade.html', 'Guide des autorisations', 'Déclaration préalable ou permis ?')],
  },
  {
    'slug': 'desamiantage',
    'nom': 'Désamiantage',
    'service': 'desamiantage',
    'titre': 'Désamiantage Paris & IDF : repérage, retrait, déchets amiantés | Cohesif BTP',
    'description': 'Désamiantage à Paris, en Île-de-France et partout en France : repérage amiante avant travaux, plan de retrait, confinement, retrait, traçabilité des déchets (BSDA) et dossier de fin. Devis sous 48h.',
    'badge': 'Désamiantage · Paris, Île-de-France et toute la France',
    'h1': 'Désamiantage : <span class="accent">repérage, retrait et déchets, dans le respect strict de la réglementation.</span>',
    'lead': 'Avant de rénover ou de démolir un bâtiment construit avant 1997, l\'amiante doit être repéré, puis retiré dans un cadre très encadré. Nous organisons toute l\'opération, du repérage au dossier de fin, pour que vos travaux démarrent en sécurité.',
    'trust': ['Devis détaillé sous 48h', 'Démarches réglementaires gérées', 'Traçabilité complète des déchets', 'Dossier de fin d\'opération'],
    'carte_titre': 'L\'opération complète',
    'carte': ['Repérage amiante avant travaux', 'Plan de retrait et démarches', 'Confinement et décontamination', 'Retrait ou encapsulage', 'Évacuation des déchets (BSDA)', 'Mesures et dossier de fin'],
    'prestations_titre': 'Une opération amiante, <span class="accent">de bout en bout.</span>',
    'prestations_desc': 'Chaque étape est réglementée : nous la préparons, la réalisons avec des intervenants habilités et vous en remettons les preuves.',
    'prestations': [
      ('search', 'Repérage avant travaux', 'Repérage amiante avant travaux (RAT) par un opérateur certifié, ciblé sur la zone des travaux prévus.'),
      ('doc', 'Plan de retrait', 'Mode opératoire, plan de retrait et transmission aux organismes de prévention dans les délais réglementaires.'),
      ('shield', 'Confinement', 'Zone confinée en dépression, sas de décontamination, protections individuelles et surveillance de l\'air.'),
      ('tool', 'Retrait ou encapsulage', 'Dépose des matériaux amiantés (fibrociment, dalles, colles, enduits, calorifugeages) ou encapsulage quand il est adapté.'),
      ('truck', 'Déchets tracés', 'Conditionnement étanche, bordereau de suivi des déchets amiantés (BSDA) et élimination en installation agréée.'),
      ('check', 'Restitution & dossier', 'Examen visuel, mesure d\'empoussièrement avant restitution de la zone et dossier de fin d\'opération.'),
    ],
    'etapes': [
      ('Repérage', 'Le repérage avant travaux localise les matériaux amiantés de la zone concernée.'),
      ('Plan de retrait', 'Le plan est établi et transmis aux organismes de prévention avant le chantier.'),
      ('Chantier confiné', 'Retrait en zone confinée, avec contrôles de l\'air pendant toute l\'intervention.'),
      ('Restitution', 'Mesures libératoires, évacuation tracée des déchets et remise du dossier de fin.'),
    ],
    'savoir_titre': 'Amiante : <span class="accent">ce que dit la réglementation.</span>',
    'savoir': [
      'L\'amiante est interdit en France depuis 1997 : les bâtiments dont le permis de construire est antérieur au 1er juillet 1997 peuvent en contenir.',
      'Avant des travaux dans un bâtiment ancien, le donneur d\'ordre (souvent le propriétaire) doit faire réaliser un repérage amiante avant travaux.',
      'Le retrait de matériaux amiantés est réservé à des entreprises certifiées ; les autres interventions exigent des opérateurs formés.',
      'Ne percez, ne poncez et ne cassez jamais un matériau suspect : c\'est en le dégradant qu\'il libère des fibres.',
      'Les déchets amiantés ne vont pas en déchetterie classique : ils suivent une filière dédiée, tracée par un bordereau (BSDA).',
    ],
    'savoir_carte': ('Où se cache l\'amiante ?', 'Plaques de fibrociment en toiture ou en bardage, dalles de sol vinyle et leurs colles, conduits, enduits, flocages, calorifugeages de tuyaux, joints de chaudière : un repérage fait le point avant les travaux.', 'renovation-appartement-maison.html', 'La rénovation après désamiantage'),
    'pros': [
      ('Toute l\'opération', 'Repérage, démarches, retrait, déchets et dossier de fin : un seul interlocuteur pour une procédure complexe.'),
      ('Justificatifs remis', 'Rapports de repérage, plan de retrait, mesures d\'air, bordereaux de déchets : vous gardez la preuve de chaque étape.'),
      ('Les travaux enchaînent', 'Une fois la zone restituée, nos équipes de rénovation, de toiture ou de gros œuvre prennent le relais sans délai.'),
    ],
    'faq': [
      ('Comment savoir s\'il y a de l\'amiante chez moi ?', 'Si le permis de construire du bâtiment est antérieur au 1er juillet 1997, de l\'amiante est possible. Seul un repérage réalisé par un opérateur certifié, avec analyse des prélèvements en laboratoire, permet de le confirmer.'),
      ('Le repérage amiante avant travaux est-il obligatoire ?', 'Oui, avant des travaux dans un immeuble bâti susceptible de contenir de l\'amiante, le donneur d\'ordre doit faire réaliser un repérage adapté à la nature et au périmètre des travaux, sauf cas d\'exemption prévus par la réglementation.'),
      ('Combien de temps dure un désamiantage ?', 'L\'intervention elle-même prend de quelques jours à quelques semaines selon les quantités. Il faut y ajouter la préparation : le plan de retrait doit être transmis aux organismes de prévention au moins un mois avant le début du chantier, sauf urgence.'),
      ('Peut-on rester dans le logement pendant le retrait ?', 'La zone de travaux est confinée et interdite d\'accès. Selon sa taille et sa position, le reste du logement peut parfois rester occupé ; c\'est défini dans le plan de retrait.'),
      ('Que deviennent les déchets amiantés ?', 'Ils sont conditionnés en emballages étanches et étiquetés, puis acheminés vers une installation de stockage agréée. Chaque envoi est suivi par un bordereau de suivi des déchets amiantés (BSDA), qui vous est remis.'),
    ],
    'form_travaux': ['Repérage avant travaux', 'Retrait de toiture fibrociment', 'Retrait de dalles / colles de sol', 'Désamiantage avant rénovation', 'Désamiantage avant démolition', 'Autre'],
    'form_placeholder': 'Type de bâtiment, année de construction, matériaux suspectés, surface, rapport de repérage existant…',
    'liens': [('renovation-appartement-maison.html', 'Rénovation complète', 'Appartements, maisons, bureaux'), ('toiture-couverture.html', 'Toiture & couverture', 'Nouvelle couverture après fibrociment'), ('gros-oeuvre-maconnerie.html', 'Gros œuvre & démolition', 'Démolition, curage, structure')],
  },
  {
    'slug': 'isolation-combles-murs',
    'nom': 'Isolation',
    'service': 'second-oeuvre',
    'titre': 'Isolation des combles, murs et planchers : thermique et acoustique | Cohesif BTP',
    'description': 'Isolation des combles perdus et aménagés, des murs par l\'intérieur, des planchers bas et isolation acoustique à Paris, en Île-de-France et partout en France. Matériaux, résistance thermique, aides 2026. Devis sous 48h.',
    'badge': 'Isolation · Paris, Île-de-France et toute la France',
    'h1': 'Isolation des combles, des murs et des planchers : <span class="accent">moins de pertes, plus de confort, été comme hiver.</span>',
    'lead': 'Une maison mal isolée perd sa chaleur par le toit, les murs et le sol. Cohesif BTP isole vos combles, vos murs par l\'intérieur et vos planchers avec l\'isolant adapté, l\'étanchéité à l\'air soignée et la ventilation vérifiée.',
    'trust': ['Devis détaillé sous 48h', 'Résistance thermique indiquée', 'Aides possibles', 'Étanchéité à l\'air soignée'],
    'carte_titre': 'Ce que nous isolons',
    'carte': ['Combles perdus (soufflage)', 'Combles aménagés et rampants', 'Murs par l\'intérieur', 'Planchers bas, caves, vides sanitaires', 'Isolation acoustique', 'Ventilation (VMC)'],
    'prestations_titre': 'Chaque paroi, <span class="accent">avec le bon isolant.</span>',
    'prestations_desc': 'Le toit, les murs et le sol ne s\'isolent pas de la même façon : nous choisissons la technique et le matériau selon la paroi, l\'humidité et votre budget.',
    'prestations': [
      ('home', 'Combles perdus', 'Isolant soufflé (laine minérale, ouate de cellulose) en couche épaisse : la solution la plus rentable pour commencer.'),
      ('roof', 'Rampants & combles aménagés', 'Isolation entre et sous chevrons, pare-vapeur continu, finition plaque de plâtre prête à peindre.'),
      ('bricks', 'Murs par l\'intérieur', 'Doublage sur ossature métallique avec laine minérale ou complexe isolant, traitement des ponts thermiques.'),
      ('layers', 'Planchers bas', 'Isolation en sous-face de plancher sur cave, garage ou vide sanitaire : un sol plus chaud sans travaux à l\'étage.'),
      ('wave', 'Isolation acoustique', 'Cloisons et doublages acoustiques, plafonds désolidarisés, laine de roche haute densité contre les bruits.'),
      ('wind', 'Ventilation', 'Contrôle ou pose de VMC : un logement mieux isolé doit être bien ventilé pour éviter condensation et moisissures.'),
    ],
    'etapes': [
      ('Diagnostic', 'Parois à isoler, humidité, ventilation existante, contraintes d\'accès et d\'épaisseur.'),
      ('Choix & devis', 'Isolant, épaisseur et résistance thermique (R) indiqués au devis, avec les aides possibles.'),
      ('Pose soignée', 'Isolant continu, pare-vapeur et étanchéité à l\'air traités aux jonctions et aux passages de gaines.'),
      ('Contrôle & attestation', 'Vérification finale et documents nécessaires au versement des aides.'),
    ],
    'savoir_titre': 'Bien isoler, <span class="accent">c\'est aussi une question de chiffres.</span>',
    'savoir': [
      'La performance d\'un isolant se lit à sa résistance thermique R : plus elle est élevée, mieux la paroi est isolée.',
      'Pour ouvrir droit aux aides, les seuils usuels sont R ≥ 7 en combles perdus, R ≥ 6 en rampants, R ≥ 3,7 pour les murs et R ≥ 3 pour les planchers bas.',
      'Le pare-vapeur se place côté chaud et doit être continu : un trou mal traité suffit à mouiller l\'isolant.',
      'Isoler sans ventiler crée de la condensation : la ventilation est vérifiée à chaque chantier.',
      'En 2026, l\'isolation des combles et rampants reste aidée par MaPrimeRénov\' par geste ; celle des murs passe par la prime CEE et la TVA à 5,5 %.',
    ],
    'savoir_carte': ('Combien d\'aides pour vous ?', 'MaPrimeRénov\', prime CEE, TVA à 5,5 % et éco-prêt à taux zéro : estimez vos aides en une minute, sans laisser vos coordonnées.', 'aides-financement.html#simulateur', 'Simuler mes aides'),
    'pros': [
      ('L\'isolant adapté', 'Laine de roche, laine de verre, ouate de cellulose, fibre de bois : nous conseillons selon la paroi, l\'humidité et le confort d\'été.'),
      ('Aides intégrées', 'Devis conforme aux exigences des aides, résistance thermique indiquée, documents fournis pour le versement.'),
      ('Isolation et finitions', 'Plaques de plâtre, bandes, peinture : nos équipes de second œuvre livrent des pièces prêtes à vivre.'),
    ],
    'faq': [
      ('Quelle partie de la maison isoler en premier ?', 'Le toit, en général : une grande part de la chaleur d\'une maison mal isolée s\'échappe par les combles, et leur isolation est souvent la plus rentable. Viennent ensuite les murs, puis les planchers bas.'),
      ('Combien coûte l\'isolation des combles ?', 'À titre indicatif, l\'isolation de combles perdus par soufflage se situe souvent entre 20 et 40 € HT par m², et celle de rampants de combles aménagés entre 50 et 100 € HT par m², finitions comprises ou non selon les cas. Le devis après visite donne le prix exact, aides déduites.'),
      ('Isolation par l\'intérieur ou par l\'extérieur ?', 'L\'isolation par l\'intérieur coûte moins cher mais réduit un peu la surface habitable. L\'isolation par l\'extérieur traite mieux les ponts thermiques et refait la façade, mais elle est plus coûteuse et pas toujours autorisée. Voir notre guide sur l\'isolation par l\'extérieur.'),
      ('Quel isolant choisir ?', 'La laine de roche et la laine de verre offrent un bon rapport performance-prix ; la laine de roche résiste aussi au feu et améliore l\'acoustique. La ouate de cellulose et la fibre de bois apportent un meilleur confort d\'été grâce à leur inertie.'),
      ('L\'isolation des murs est-elle aidée en 2026 ?', 'Elle n\'est plus financée par MaPrimeRénov\' par geste en 2026, mais reste aidée par la prime CEE, la TVA à 5,5 % et l\'éco-prêt à taux zéro, et par MaPrimeRénov\' dans une rénovation d\'ampleur.'),
    ],
    'form_travaux': ['Combles perdus', 'Combles aménagés / rampants', 'Murs par l\'intérieur', 'Planchers bas', 'Isolation acoustique', 'Ventilation (VMC)', 'Autre'],
    'form_placeholder': 'Type de logement, surface à isoler, chauffage actuel, délai souhaité…',
    'liens': [('aides-financement.html', 'Aides & financement', 'Simulez vos aides 2026'), ('guide-isolation-exterieure-ite.html', 'Isolation par l\'extérieur', 'Prix, intérêt et aides'), ('boutique-laine-de-roche.html', 'Laine de roche', 'Panneaux 40 à 120 kg/m³ en boutique')],
  },
]
