# Cohesif BTP — contenu des pages locales (lu par tools/build_zones.py)
# Une page par département d'Île-de-France, avec un contenu propre à chacun (bâti, règles, risques, villes).
# Ne pas dupliquer un texte d'une page à l'autre : Google pénalise les pages locales quasi identiques.
# Clés de « services » : toiture, facade, renovation, gros-oeuvre, isolation, desamiantage.

ZONES = [
  {
    'slug': 'travaux-paris-75',
    'nom': 'Paris', 'code': '75', 'dans': 'à Paris',
    'titre': 'Couvreur, ravalement et rénovation à Paris (75) | Cohesif BTP',
    'description': 'Entreprise de travaux à Paris (75) : toiture zinc et ardoise, ravalement obligatoire, rénovation d\'appartement, désamiantage, gros œuvre. Siège dans le 15e, intervention dans les 20 arrondissements, devis sous 48h.',
    'h1': 'Travaux à Paris : <span class="accent">toits en zinc, façades en pierre et appartements anciens.</span>',
    'lead': 'Notre siège est rue de la Croix-Nivert, dans le 15e. Nous connaissons les contraintes parisiennes : copropriétés, Architecte des Bâtiments de France, échafaudages sur la voie publique et accès difficiles.',
    'bati': [
      'Paris est d\'abord une ville d\'immeubles en copropriété : pierre de taille haussmannienne, immeubles de rapport en brique ou en moellons enduits, faubourgs plus modestes et constructions des années 1950 à 1970. Chaque époque a ses matériaux et ses pathologies.',
      'Les toits parisiens sont majoritairement couverts en zinc, avec de l\'ardoise sur les brisis des combles à la Mansart. Le travail se fait souvent depuis des échafaudages en façade ou des accès par cour, avec des chéneaux, lucarnes et souches de cheminée à reprendre.',
      'À l\'intérieur, les appartements anciens réservent leurs surprises : planchers bois, cloisons en carreaux de plâtre, colonnes d\'eau vétustes, et matériaux amiantés possibles dans tout immeuble dont le permis est antérieur à 1997.',
    ],
    'services': {
      'toiture': 'Couverture zinc et ardoise, chéneaux, lucarnes, souches, fenêtres de toit : le savoir-faire des toits parisiens.',
      'facade': 'Ravalement obligatoire tous les dix ans, pierre de taille, enduits, déclaration préalable et autorisation de voirie.',
      'renovation': 'Rénovation complète d\'appartement en copropriété, avec le respect des horaires et des parties communes.',
      'gros-oeuvre': 'Ouverture de murs porteurs avec étude de structure, reprise de planchers, surélévations quand le PLU le permet.',
      'isolation': 'Isolation des combles et des rampants sous zinc, doublages intérieurs quand la façade ne peut pas être isolée.',
      'desamiantage': 'Repérage et retrait avant travaux dans les immeubles d\'avant 1997 : dalles, colles, conduits, enduits.',
    },
    'vigilance': [
      'Le ravalement est obligatoire au moins tous les dix ans et passe par une déclaration préalable à Paris.',
      'Une grande partie de Paris est en secteur protégé : l\'Architecte des Bâtiments de France donne son avis sur les matériaux et les teintes.',
      'Un échafaudage ou une benne sur le trottoir nécessite une autorisation d\'occupation du domaine public auprès de la Ville.',
      'En copropriété, tout ce qui touche aux parties communes ou à l\'aspect extérieur passe par l\'assemblée générale.',
    ],
    'villes_titre': 'Les 20 arrondissements',
    'villes': ['Paris 1er', 'Paris 2e', 'Paris 3e', 'Paris 4e', 'Paris 5e', 'Paris 6e', 'Paris 7e', 'Paris 8e', 'Paris 9e', 'Paris 10e', 'Paris 11e', 'Paris 12e', 'Paris 13e', 'Paris 14e', 'Paris 15e', 'Paris 16e', 'Paris 17e', 'Paris 18e', 'Paris 19e', 'Paris 20e'],
    'faq': [
      ('Intervenez-vous dans tous les arrondissements de Paris ?', 'Oui, dans les 20 arrondissements. Notre siège est dans le 15e, rue de la Croix-Nivert, ce qui nous permet des visites rapides partout dans Paris.'),
      ('Le ravalement est-il obligatoire à Paris ?', 'Oui. Les façades doivent être ravalées au moins une fois tous les dix ans, et le ravalement est soumis à déclaration préalable. La Ville peut adresser une injonction au propriétaire ou au syndic.'),
      ('Gérez-vous l\'autorisation pour l\'échafaudage sur le trottoir ?', 'Oui. La demande d\'occupation du domaine public auprès de la Ville de Paris fait partie de nos démarches, comme la déclaration préalable de travaux.'),
    ],
    'guides': ['guide-ravalement-obligatoire-paris', 'guide-prix-ravalement-facade-paris'],
  },
  {
    'slug': 'travaux-hauts-de-seine-92',
    'nom': 'Hauts-de-Seine', 'code': '92', 'dans': 'dans les Hauts-de-Seine',
    'titre': 'Couvreur, ravalement et rénovation dans les Hauts-de-Seine (92) | Cohesif BTP',
    'description': 'Travaux dans les Hauts-de-Seine (92) : toiture, ravalement, rénovation de maison et d\'appartement, extension, isolation, désamiantage. Boulogne, Neuilly, Issy, Rueil, Antony… Devis sous 48h.',
    'h1': 'Travaux dans les Hauts-de-Seine : <span class="accent">immeubles bourgeois, villas sur les coteaux et pavillons.</span>',
    'lead': 'À quelques minutes de notre siège du 15e, nous intervenons dans tout le 92, de Boulogne à Antony et de Neuilly à Rueil-Malmaison.',
    'bati': [
      'Le nord et l\'est du département prolongent Paris : immeubles haussmanniens et post-haussmanniens à Neuilly, Levallois ou Boulogne, avec les mêmes enjeux de copropriété et de façades en pierre ou en brique.',
      'Sur les coteaux de la Seine, à Meudon, Sèvres, Saint-Cloud ou Suresnes, on trouve des villas et maisons de caractère, souvent en meulière, construites sur des terrains en pente : l\'accès au chantier et la gestion des eaux pluviales comptent autant que les travaux eux-mêmes.',
      'Le sud, d\'Antony à Clamart en passant par Sceaux, est plus pavillonnaire, avec de nombreuses maisons des années 1920 à 1970 qui gagnent à être isolées, agrandies ou surélevées.',
    ],
    'services': {
      'toiture': 'Ardoise et tuile sur les villas, zinc sur les immeubles : réfection, zinguerie et fenêtres de toit.',
      'facade': 'Pierre, brique ou meulière : nettoyage adapté, rejointoiement et enduits respectueux du bâti.',
      'renovation': 'Rénovation d\'appartements et de maisons de caractère, de la redistribution aux finitions.',
      'gros-oeuvre': 'Extensions, surélévations et ouvertures de murs porteurs, très demandées dans le sud du département.',
      'isolation': 'Combles, rampants et doublages pour des pavillons anciens souvent peu isolés.',
      'desamiantage': 'Repérage et retrait avant rénovation dans les maisons et immeubles construits avant 1997.',
    },
    'vigilance': [
      'De nombreux secteurs sont protégés (abords de monuments historiques, sites patrimoniaux) : l\'avis de l\'Architecte des Bâtiments de France est fréquent.',
      'Sur les coteaux, la pente du terrain complique l\'accès des engins et l\'installation des échafaudages : c\'est prévu dès la visite.',
      'Une surélévation suppose de vérifier la capacité des murs et fondations existants, surtout sur les maisons en meulière.',
      'Chaque commune a son PLU : hauteurs, emprise au sol et aspect des toitures varient d\'une ville à l\'autre.',
    ],
    'villes_titre': 'Quelques villes où nous intervenons',
    'villes': ['Boulogne-Billancourt', 'Nanterre', 'Courbevoie', 'Colombes', 'Asnières-sur-Seine', 'Rueil-Malmaison', 'Issy-les-Moulineaux', 'Levallois-Perret', 'Neuilly-sur-Seine', 'Antony', 'Clichy', 'Clamart', 'Montrouge', 'Suresnes', 'Meudon', 'Puteaux', 'Châtillon', 'Sèvres', 'Saint-Cloud', 'Vanves', 'Malakoff', 'Bagneux', 'Sceaux', 'Garches'],
    'faq': [
      ('Intervenez-vous dans tout le 92 ?', 'Oui, dans toutes les communes des Hauts-de-Seine. Notre siège, dans le 15e arrondissement, est à quelques minutes de Boulogne, Issy-les-Moulineaux et Vanves.'),
      ('Peut-on surélever une maison dans les Hauts-de-Seine ?', 'Souvent, si le PLU de la commune l\'autorise et si la structure existante peut porter la charge. Une étude de structure le vérifie avant le dépôt du permis de construire.'),
      ('Comment ravaler une façade en meulière ?', 'La meulière se nettoie en douceur et se rejointoie à la chaux ; il ne faut ni l\'enduire au ciment ni la peindre, sous peine d\'enfermer l\'humidité dans les murs.'),
    ],
    'guides': ['guide-autorisation-travaux-toiture-facade', 'guide-prix-refection-toiture'],
  },
  {
    'slug': 'travaux-seine-saint-denis-93',
    'nom': 'Seine-Saint-Denis', 'code': '93', 'dans': 'en Seine-Saint-Denis',
    'titre': 'Couvreur, ravalement et rénovation en Seine-Saint-Denis (93) | Cohesif BTP',
    'description': 'Travaux en Seine-Saint-Denis (93) : toiture, ravalement, rénovation de pavillon et d\'appartement, isolation, désamiantage, gros œuvre. Montreuil, Saint-Denis, Pantin, Aulnay… Devis sous 48h.',
    'h1': 'Travaux en Seine-Saint-Denis : <span class="accent">pavillons en meulière, immeubles et anciens sites industriels.</span>',
    'lead': 'De Montreuil à Aulnay-sous-Bois, nous rénovons pavillons, immeubles et locaux d\'activité du 93, avec une attention particulière aux sols et à l\'amiante.',
    'bati': [
      'Le 93 compte un grand nombre de pavillons du début du XXe siècle en meulière ou en brique, souvent modifiés au fil des décennies : extensions, combles aménagés, réseaux refaits par morceaux. Une rénovation commence par un diagnostic complet de l\'existant.',
      'Les grands ensembles et les immeubles construits entre 1950 et 1997 sont nombreux : isolation, menuiseries et repérage amiante y sont des sujets centraux avant tout chantier.',
      'L\'est du département, de Montreuil à Gagny en passant par Romainville et Bagnolet, est marqué par d\'anciennes carrières de gypse. Les secteurs concernés font l\'objet de règles particulières et d\'études de sol renforcées avant de construire ou d\'agrandir.',
    ],
    'services': {
      'toiture': 'Tuiles mécaniques des pavillons, toitures-terrasses des immeubles : réparation, réfection et étanchéité.',
      'facade': 'Ravalement de pavillons et d\'immeubles, traitement des fissures et isolation par l\'extérieur.',
      'renovation': 'Rénovation complète de pavillons et d\'appartements, remise aux normes électriques et plomberie.',
      'gros-oeuvre': 'Extensions et reprises de fondations, avec étude de sol adaptée aux secteurs de carrières.',
      'isolation': 'Isolation des combles, des murs et des planchers bas de pavillons souvent énergivores.',
      'desamiantage': 'Repérage et retrait dans les immeubles et locaux d\'avant 1997, fréquents dans le département.',
    },
    'vigilance': [
      'Dans les secteurs d\'anciennes carrières de gypse, une étude de sol est indispensable avant une extension ou une construction.',
      'Beaucoup de bâtiments datent d\'avant 1997 : le repérage amiante avant travaux est presque toujours nécessaire.',
      'Les anciens sites industriels réhabilités peuvent présenter des sols pollués : à vérifier avant tout terrassement.',
      'Les pavillons transformés au fil du temps cachent souvent des réseaux électriques non conformes à reprendre.',
    ],
    'villes_titre': 'Quelques villes où nous intervenons',
    'villes': ['Saint-Denis', 'Montreuil', 'Aubervilliers', 'Aulnay-sous-Bois', 'Drancy', 'Noisy-le-Grand', 'Pantin', 'Bondy', 'Épinay-sur-Seine', 'Le Blanc-Mesnil', 'Sevran', 'Bobigny', 'Rosny-sous-Bois', 'Livry-Gargan', 'Saint-Ouen-sur-Seine', 'Noisy-le-Sec', 'Gagny', 'Villemomble', 'Les Lilas', 'Le Raincy', 'Bagnolet', 'Romainville'],
    'faq': [
      ('Intervenez-vous dans toute la Seine-Saint-Denis ?', 'Oui, dans toutes les communes du 93, pour les particuliers, les copropriétés et les professionnels.'),
      ('Faut-il une étude de sol pour une extension en Seine-Saint-Denis ?', 'Elle est fortement recommandée partout et indispensable dans les secteurs d\'anciennes carrières de gypse, où des règles particulières s\'appliquent. Le service urbanisme de la mairie indique si votre terrain est concerné.'),
      ('Mon pavillon des années 1960 contient-il de l\'amiante ?', 'C\'est possible : tout bâtiment dont le permis est antérieur au 1er juillet 1997 peut en contenir (dalles de sol, colles, conduits, fibrociment). Un repérage avant travaux permet de le savoir.'),
    ],
    'guides': ['guide-choisir-couvreur-eviter-arnaques', 'guide-isolation-exterieure-ite'],
  },
  {
    'slug': 'travaux-val-de-marne-94',
    'nom': 'Val-de-Marne', 'code': '94', 'dans': 'dans le Val-de-Marne',
    'titre': 'Couvreur, ravalement et rénovation dans le Val-de-Marne (94) | Cohesif BTP',
    'description': 'Travaux dans le Val-de-Marne (94) : toiture, ravalement, rénovation, extension, isolation, désamiantage. Vincennes, Saint-Maur, Créteil, Nogent, Vitry… Devis sous 48h.',
    'h1': 'Travaux dans le Val-de-Marne : <span class="accent">bords de Marne, maisons de caractère et sous-sols à surveiller.</span>',
    'lead': 'De Vincennes à Créteil et de Nogent-sur-Marne à Vitry-sur-Seine, nous intervenons dans tout le 94 pour la toiture, la façade et la rénovation.',
    'bati': [
      'Les bords de Marne, de Nogent au Perreux et à Saint-Maur-des-Fossés, alignent maisons de villégiature et pavillons en meulière de la Belle Époque, aux toitures en tuile plate ou mécanique et aux décors de façade soignés.',
      'Près de Paris, Vincennes, Saint-Mandé ou Charenton présentent des immeubles de rapport proches des immeubles parisiens, tandis que Créteil, Vitry ou Champigny comptent de nombreux ensembles d\'après-guerre.',
      'Une partie du département est concernée par le risque d\'inondation de la Seine et de la Marne, et certaines communes proches de Paris par d\'anciennes carrières souterraines : deux points à intégrer dans tout projet touchant au sous-sol ou aux fondations.',
    ],
    'services': {
      'toiture': 'Tuiles plates et mécaniques des maisons de bord de Marne, zinc des immeubles : réfection et zinguerie.',
      'facade': 'Ravalement de façades décorées, meulière et brique, avec le respect des modénatures d\'origine.',
      'renovation': 'Rénovation de maisons anciennes et d\'appartements, de la cave aux combles.',
      'gros-oeuvre': 'Extensions, reprises en sous-œuvre et travaux de structure adaptés aux sols du secteur.',
      'isolation': 'Isolation des combles et des planchers bas, y compris sur caves et sous-sols humides.',
      'desamiantage': 'Repérage et retrait avant rénovation dans les ensembles et maisons d\'avant 1997.',
    },
    'vigilance': [
      'En zone inondable, le plan de prévention des risques (PPRI) peut imposer des règles pour les extensions et les sous-sols.',
      'Dans les secteurs d\'anciennes carrières souterraines, une étude de sol précède toute extension ou reprise de fondation.',
      'Les caves et sous-sols humides demandent un traitement de l\'humidité avant d\'isoler un plancher bas.',
      'Les façades décorées des maisons de bord de Marne se ravalent à l\'identique : pas d\'enduit couvrant sur la meulière.',
    ],
    'villes_titre': 'Quelques villes où nous intervenons',
    'villes': ['Vitry-sur-Seine', 'Créteil', 'Champigny-sur-Marne', 'Saint-Maur-des-Fossés', 'Ivry-sur-Seine', 'Maisons-Alfort', 'Fontenay-sous-Bois', 'Villejuif', 'Vincennes', 'Nogent-sur-Marne', 'Le Perreux-sur-Marne', 'Charenton-le-Pont', 'Saint-Mandé', 'Cachan', 'L\'Haÿ-les-Roses', 'Choisy-le-Roi', 'Alfortville', 'Sucy-en-Brie', 'Thiais', 'Joinville-le-Pont'],
    'faq': [
      ('Intervenez-vous dans tout le Val-de-Marne ?', 'Oui, dans toutes les communes du 94, pour les maisons, les copropriétés et les locaux professionnels.'),
      ('Peut-on agrandir une maison en zone inondable ?', 'Parfois, sous conditions : le plan de prévention du risque inondation (PPRI) fixe ce qui est autorisé (surface, hauteur du plancher, sous-sol). Nous vérifions le zonage de votre parcelle avant de chiffrer.'),
      ('Comment isoler le plancher d\'une maison sur cave humide ?', 'On traite d\'abord l\'humidité (ventilation de la cave, drainage si besoin), puis on isole en sous-face du plancher avec un isolant adapté aux locaux humides.'),
    ],
    'guides': ['guide-prix-refection-toiture', 'guide-prix-ravalement-facade-paris'],
  },
  {
    'slug': 'travaux-yvelines-78',
    'nom': 'Yvelines', 'code': '78', 'dans': 'dans les Yvelines',
    'titre': 'Couvreur, ravalement et rénovation dans les Yvelines (78) | Cohesif BTP',
    'description': 'Travaux dans les Yvelines (78) : toiture ardoise et tuile plate, ravalement, rénovation de maison, extension, isolation, désamiantage. Versailles, Saint-Germain, Le Vésinet, Rambouillet… Devis sous 48h.',
    'h1': 'Travaux dans les Yvelines : <span class="accent">demeures de caractère, secteurs protégés et grandes maisons.</span>',
    'lead': 'De Versailles à Saint-Germain-en-Laye et jusqu\'à Rambouillet, nous rénovons les toitures, façades et intérieurs des maisons et copropriétés des Yvelines.',
    'bati': [
      'Les Yvelines concentrent un patrimoine exceptionnel : Versailles, Saint-Germain-en-Laye, Maisons-Laffitte ou Le Vésinet imposent des règles strictes d\'aspect, et les chantiers s\'y préparent avec l\'Architecte des Bâtiments de France.',
      'Les maisons bourgeoises et les villas y sont souvent couvertes d\'ardoise ou de tuile plate, avec des lucarnes, des épis et une zinguerie travaillée qu\'il faut savoir refaire à l\'identique.',
      'Au sud, la Haute Vallée de Chevreuse est un parc naturel régional dont la charte encadre l\'aspect des constructions. Ailleurs, les quartiers pavillonnaires des années 1960 à 1990 attendent surtout isolation et rénovation énergétique.',
    ],
    'services': {
      'toiture': 'Ardoise, tuile plate et zinguerie travaillée : réfection à l\'identique et lucarnes.',
      'facade': 'Ravalement de pierre, d\'enduits à la chaux et de façades protégées, dossier pour l\'ABF compris.',
      'renovation': 'Rénovation de grandes maisons et de demeures anciennes, intérieur et extérieur.',
      'gros-oeuvre': 'Extensions et dépendances intégrées au bâti existant, dans le respect du PLU.',
      'isolation': 'Isolation des combles et des rampants sous ardoise, isolation des pavillons des années 1970.',
      'desamiantage': 'Repérage et retrait avant travaux, notamment des toitures et bardages en fibrociment.',
    },
    'vigilance': [
      'Une grande partie des communes historiques est en secteur protégé : matériaux, teintes et menuiseries sont soumis à l\'avis de l\'ABF.',
      'Dans le parc naturel régional de la Haute Vallée de Chevreuse, la charte du parc oriente l\'aspect des constructions.',
      'Les toitures en ardoise et tuile plate se refont avec des matériaux équivalents à l\'existant dans les secteurs protégés.',
      'Une partie du département est exposée au retrait-gonflement des argiles : à étudier avant toute extension.',
    ],
    'villes_titre': 'Quelques villes où nous intervenons',
    'villes': ['Versailles', 'Saint-Germain-en-Laye', 'Le Vésinet', 'Chatou', 'Maisons-Laffitte', 'Le Chesnay-Rocquencourt', 'Sartrouville', 'Houilles', 'Poissy', 'Conflans-Sainte-Honorine', 'Montigny-le-Bretonneux', 'Guyancourt', 'Vélizy-Villacoublay', 'Saint-Cyr-l\'École', 'Plaisir', 'Rambouillet', 'Mantes-la-Jolie', 'Les Mureaux'],
    'faq': [
      ('Intervenez-vous à Versailles et dans les secteurs protégés ?', 'Oui. Nous préparons le dossier de déclaration préalable avec les matériaux et teintes attendus, et nous intégrons les prescriptions de l\'Architecte des Bâtiments de France au devis.'),
      ('Faut-il refaire une toiture en ardoise à l\'identique ?', 'En secteur protégé, c\'est en général exigé : même matériau, même format et même mode de pose. Ailleurs, un changement reste possible avec une déclaration préalable.'),
      ('Intervenez-vous dans tout le département ?', 'Oui, de la boucle de la Seine à la vallée de Chevreuse et jusqu\'au Mantois.'),
    ],
    'guides': ['guide-autorisation-travaux-toiture-facade', 'guide-prix-refection-toiture'],
  },
  {
    'slug': 'travaux-essonne-91',
    'nom': 'Essonne', 'code': '91', 'dans': 'en Essonne',
    'titre': 'Couvreur, ravalement et rénovation en Essonne (91) | Cohesif BTP',
    'description': 'Travaux en Essonne (91) : toiture, ravalement, rénovation de pavillon, extension, isolation, désamiantage. Massy, Palaiseau, Évry, Yerres, Gif-sur-Yvette… Devis sous 48h.',
    'h1': 'Travaux en Essonne : <span class="accent">pavillons à isoler, sols argileux et maisons de vallée.</span>',
    'lead': 'De Massy à Évry-Courcouronnes et de Gif-sur-Yvette à Yerres, nous intervenons dans toute l\'Essonne pour rénover, isoler et agrandir.',
    'bati': [
      'L\'Essonne est un département largement pavillonnaire : maisons en meulière autour des gares historiques, puis grands lotissements des années 1960 à 1990 dont les combles, les murs et les menuiseries sont souvent à reprendre.',
      'Les vallées de l\'Yvette, de l\'Orge et de l\'Yerres abritent des maisons anciennes et des propriétés en pierre, tandis que le sud du département, plus rural, compte corps de ferme et maisons de bourg.',
      'Une part importante du territoire est exposée au retrait-gonflement des argiles : les fissures en façade y sont fréquentes après les étés secs, et toute extension commence par une étude de sol.',
    ],
    'services': {
      'toiture': 'Réfection de toitures de pavillons, tuiles mécaniques et plates, démoussage et zinguerie.',
      'facade': 'Ravalement et traitement des fissures, avec un diagnostic de leur origine avant de reboucher.',
      'renovation': 'Rénovation complète de pavillons, cuisine, salle de bain et redistribution.',
      'gros-oeuvre': 'Extensions et reprises en sous-œuvre adaptées aux sols argileux.',
      'isolation': 'Isolation des combles et des murs des pavillons des années 1960 à 1990, avec les aides possibles.',
      'desamiantage': 'Repérage et retrait avant travaux dans les maisons et bâtiments d\'avant 1997.',
    },
    'vigilance': [
      'Sur sol argileux, une fissure en façade peut venir des fondations : on en cherche la cause avant de la masquer.',
      'Une étude géotechnique est exigée pour construire une maison neuve dans les zones exposées au retrait-gonflement des argiles.',
      'Le sud du département est en partie couvert par des parcs naturels régionaux, dont les chartes orientent l\'aspect des constructions.',
      'Les pavillons des années 1970 cumulent souvent isolation faible et matériaux amiantés possibles : un bon moment pour tout traiter.',
    ],
    'villes_titre': 'Quelques villes où nous intervenons',
    'villes': ['Évry-Courcouronnes', 'Corbeil-Essonnes', 'Massy', 'Palaiseau', 'Savigny-sur-Orge', 'Sainte-Geneviève-des-Bois', 'Athis-Mons', 'Viry-Châtillon', 'Draveil', 'Yerres', 'Brunoy', 'Orsay', 'Gif-sur-Yvette', 'Montgeron', 'Juvisy-sur-Orge', 'Longjumeau', 'Les Ulis', 'Étampes'],
    'faq': [
      ('Pourquoi ma maison en Essonne se fissure-t-elle ?', 'Sur les sols argileux, l\'alternance de sécheresse et de pluie fait bouger le terrain et peut fissurer les murs. Une fissure qui s\'élargit ou traverse le mur doit être diagnostiquée : elle peut demander une reprise des fondations.'),
      ('Isoler un pavillon des années 1970 : par où commencer ?', 'Par les combles en général, puis les murs et les menuiseries. Les aides 2026 couvrent une partie de la dépense : notre simulateur vous en donne une estimation.'),
      ('Intervenez-vous dans tout le 91 ?', 'Oui, du nord urbanisé au sud plus rural, pour les particuliers comme pour les professionnels.'),
    ],
    'guides': ['guide-isolation-exterieure-ite', 'guide-prix-refection-toiture'],
  },
  {
    'slug': 'travaux-val-d-oise-95',
    'nom': 'Val-d\'Oise', 'code': '95', 'dans': 'dans le Val-d\'Oise',
    'titre': 'Couvreur, ravalement et rénovation dans le Val-d\'Oise (95) | Cohesif BTP',
    'description': 'Travaux dans le Val-d\'Oise (95) : toiture tuile plate et ardoise, ravalement, rénovation, extension, isolation, désamiantage. Argenteuil, Cergy, Pontoise, Enghien, Montmorency… Devis sous 48h.',
    'h1': 'Travaux dans le Val-d\'Oise : <span class="accent">maisons du Vexin, villas anciennes et pavillons.</span>',
    'lead': 'D\'Argenteuil à Cergy-Pontoise et de Montmorency à L\'Isle-Adam, nous intervenons dans tout le Val-d\'Oise pour la toiture, la façade et la rénovation.',
    'bati': [
      'L\'ouest du département appartient au parc naturel régional du Vexin français : maisons en pierre calcaire, toits de tuile plate et corps de ferme, que l\'on restaure avec des matériaux compatibles et en accord avec la charte du parc.',
      'La vallée de Montmorency, Enghien-les-Bains ou L\'Isle-Adam comptent de belles villas anciennes aux façades décorées et aux toitures complexes, souvent en secteur protégé.',
      'Le reste du département, d\'Argenteuil à Sarcelles et à Cergy, associe pavillons, copropriétés et ensembles plus récents, avec de forts besoins d\'isolation et de rénovation énergétique.',
    ],
    'services': {
      'toiture': 'Tuile plate du Vexin, ardoise des villas, tuile mécanique des pavillons : réfection et réparation.',
      'facade': 'Ravalement de pierre calcaire, enduits à la chaux et façades de villas décorées.',
      'renovation': 'Rénovation de maisons anciennes, de corps de ferme et d\'appartements.',
      'gros-oeuvre': 'Extensions et transformations de dépendances, dans le respect du bâti d\'origine.',
      'isolation': 'Isolation adaptée aux murs anciens en pierre, qui doivent pouvoir respirer.',
      'desamiantage': 'Repérage et retrait, notamment des toitures de hangars et dépendances en fibrociment.',
    },
    'vigilance': [
      'Dans le parc naturel régional du Vexin français, la charte du parc oriente matériaux, teintes et volumes.',
      'Les murs anciens en pierre se traitent avec des enduits et isolants perméables à la vapeur d\'eau, jamais au ciment.',
      'Plusieurs villes historiques sont en secteur protégé : l\'avis de l\'Architecte des Bâtiments de France est requis.',
      'Une partie du département est exposée au retrait-gonflement des argiles : étude de sol avant toute extension.',
    ],
    'villes_titre': 'Quelques villes où nous intervenons',
    'villes': ['Argenteuil', 'Cergy', 'Pontoise', 'Sarcelles', 'Garges-lès-Gonesse', 'Franconville', 'Bezons', 'Ermont', 'Villiers-le-Bel', 'Gonesse', 'Taverny', 'Herblay-sur-Seine', 'Sannois', 'Eaubonne', 'Montmorency', 'Enghien-les-Bains', 'Saint-Gratien', 'L\'Isle-Adam'],
    'faq': [
      ('Rénovez-vous les maisons en pierre du Vexin ?', 'Oui, avec des matériaux compatibles avec la pierre calcaire (enduits à la chaux, isolants perméables) et en tenant compte de la charte du parc naturel régional.'),
      ('Peut-on isoler un mur ancien en pierre ?', 'Oui, à condition d\'utiliser des isolants et des enduits qui laissent migrer la vapeur d\'eau (chaux, fibre de bois, chanvre). Un isolant étanche piégerait l\'humidité dans le mur.'),
      ('Intervenez-vous dans tout le Val-d\'Oise ?', 'Oui, de la vallée de Montmorency au Vexin et à la plaine de France.'),
    ],
    'guides': ['guide-autorisation-travaux-toiture-facade', 'guide-choisir-couvreur-eviter-arnaques'],
  },
  {
    'slug': 'travaux-seine-et-marne-77',
    'nom': 'Seine-et-Marne', 'code': '77', 'dans': 'en Seine-et-Marne',
    'titre': 'Couvreur, ravalement et rénovation en Seine-et-Marne (77) | Cohesif BTP',
    'description': 'Travaux en Seine-et-Marne (77) : toiture, ravalement, rénovation de maison et de longère, extension, isolation, désamiantage. Meaux, Melun, Chelles, Fontainebleau, Lagny… Devis sous 48h.',
    'h1': 'Travaux en Seine-et-Marne : <span class="accent">longères de Brie, villes nouvelles et sols argileux.</span>',
    'lead': 'Le plus grand département d\'Île-de-France : de Chelles à Fontainebleau et de Meaux à Melun, nous intervenons sur les maisons, les fermes rénovées et les copropriétés du 77.',
    'bati': [
      'La Brie et le Gâtinais sont des terres de longères, de corps de ferme et de maisons de bourg en pierre ou en moellons enduits, couvertes de tuile plate. Leur rénovation demande des matériaux et des savoir-faire adaptés au bâti ancien.',
      'Les villes nouvelles de Marne-la-Vallée et de Sénart, comme les quartiers récents autour de Meaux ou Melun, comptent surtout des maisons et copropriétés des années 1970 à 2000, pour lesquelles l\'isolation et le confort sont les priorités.',
      'La Seine-et-Marne fait partie des départements d\'Île-de-France les plus exposés au retrait-gonflement des argiles. Fissures, portes qui frottent et dallages qui bougent y sont des motifs fréquents d\'intervention.',
    ],
    'services': {
      'toiture': 'Tuile plate des longères et maisons de bourg, tuile mécanique des pavillons : réfection et zinguerie.',
      'facade': 'Ravalement, enduits à la chaux sur moellons et traitement des fissures liées aux sols.',
      'renovation': 'Rénovation de longères, de corps de ferme et de maisons, aménagement de granges et de combles.',
      'gros-oeuvre': 'Extensions, transformations de dépendances et reprises en sous-œuvre sur sol argileux.',
      'isolation': 'Isolation des combles, des murs et des planchers, adaptée au bâti ancien comme récent.',
      'desamiantage': 'Repérage et retrait, notamment des toitures de hangars et bâtiments agricoles en fibrociment.',
    },
    'vigilance': [
      'Le risque argile est élevé dans une grande partie du département : étude de sol avant toute extension.',
      'Les longères en moellons se traitent à la chaux : un enduit ciment ou une isolation étanche y crée des désordres.',
      'Fontainebleau, Provins et de nombreux bourgs ont des secteurs protégés soumis à l\'avis de l\'ABF.',
      'Les hangars et bâtiments agricoles anciens ont souvent des couvertures en fibrociment amianté.',
    ],
    'villes_titre': 'Quelques villes où nous intervenons',
    'villes': ['Meaux', 'Chelles', 'Melun', 'Pontault-Combault', 'Savigny-le-Temple', 'Champs-sur-Marne', 'Bussy-Saint-Georges', 'Torcy', 'Villeparisis', 'Le Mée-sur-Seine', 'Roissy-en-Brie', 'Combs-la-Ville', 'Fontainebleau', 'Lagny-sur-Marne', 'Serris', 'Coulommiers', 'Provins', 'Nemours'],
    'faq': [
      ('Rénovez-vous les longères et corps de ferme ?', 'Oui : toiture en tuile plate, enduits à la chaux, aménagement de granges et de combles, isolation adaptée aux murs anciens.'),
      ('Ma maison fissure : est-ce lié à l\'argile ?', 'C\'est fréquent en Seine-et-Marne. Le diagnostic des fissures (forme, évolution, position) et une étude de sol permettent d\'en trouver la cause et de choisir la bonne réparation.'),
      ('Intervenez-vous dans tout le 77 ?', 'Oui, du nord de la Brie au Gâtinais, y compris dans les communes rurales.'),
    ],
    'guides': ['guide-prix-refection-toiture', 'guide-autorisation-travaux-toiture-facade'],
  },
]
